### ISSUE TITLE
dotnet tool?

### ISSUE THREAD

**Issue by lonix1** [Taritsyn/AutoprefixerHost#3]
Any way to use this as a `dotnet tool`? Or is that planned?

**Comment by Taritsyn** [comment]
Hello!

I don't see any point in this. It's better to use the [Posts CLI](https://www.npmjs.com/package/postcss-cli) Node.js package with the [Autoprefixer](https://www.npmjs.com/package/autoprefixer) library installed (see the [official documentation](https://github.com/postcss/autoprefixer#cli)).

If Node.js is not suitable for you at all, then I recommend that you look at the [Excubo.WebCompiler](https://github.com/excubo-ag/WebCompiler) project.

**Comment by lonix1** [comment]
Thanks.

Problem is none of the tools out there are as good as your libraries (and internally they all use your libraries anyway). Inevitably they become abandonware, but yours are still around a decade later! :smile:
